---
driver:
  name: ec2
  require_chef_omnibus: 12.13.37
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test
    Operator: <%= ENV['USER'] %>

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-7

suites:
  - name: default
    driver:
      tags:
        Name: zookeeper-default
    run_list:
      - recipe[zookeeper_tester]

  - name: attributes
    driver:
      tags:
        Name: zookeeper-attributes
    run_list:
      - recipe[zookeeper_tester::attributes]
    attributes:
      zookeeper:
        env_vars:
          ZOO_LOG4J_PROP: 'INFO,ROLLINGFILE'

  - name: sysv
    driver:
      tags:
        Name: zookeeper-sysv
    run_list:
      - recipe[zookeeper_tester::sysv]
    includes:
      - centos-6.5

  - name: systemd
    driver:
      tags:
        Name: zookeeper-systemd
    run_list:
      - recipe[zookeeper_tester::systemd]
    includes:
      - centos-7

  - name: upstart
    driver:
      tags:
        Name: zookeeper-upstart
    run_list:
      - recipe[zookeeper_tester::upstart]
    includes:
      - ubuntu-14.04
